## Numpy

In [1]:
import numpy as np 

#### 1D, 2D and 3D numpy array

In [2]:
array1D = np.array([45, 2, 4, 7, 8])
array2D = np.array([[5, 4],[8, 4]])
array3D = np.array([[[1, 5],[4, 8]],[[7, 9],[5, 5]]])

In [3]:
array1D

array([45,  2,  4,  7,  8])

In [4]:
array2D

array([[5, 4],
       [8, 4]])

In [5]:
array3D

array([[[1, 5],
        [4, 8]],

       [[7, 9],
        [5, 5]]])

#### dtype

In [6]:
a = np.array([127, 128, 129, 260], dtype=np.int8)
a

array([ 127, -128, -127,    4], dtype=int8)

####  arange, linspace, eye, diag, zeros, ones

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [10]:
np.arange(2, 4, 0.3)

array([2. , 2.3, 2.6, 2.9, 3.2, 3.5, 3.8])

In [11]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [14]:
np.diag([1, 8, 3])

array([[1, 0, 0],
       [0, 8, 0],
       [0, 0, 3]])

In [15]:
np.diag([1, 8, 3],1)

array([[0, 1, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [17]:
x = np.arange(9.0).reshape(3, 3)
x

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [18]:
np.diag(x)

array([0., 4., 8.])

In [19]:
a = np.array([[8,12],[3,7]])
np.diag(a)

array([8, 7])

In [20]:
np.zeros((3, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [23]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### mutable or immutable ???

In [26]:
a = np.array([1, 2, 3, 4, 5, 6]) # numpy arrays are mutable 
b = a[:2]
b += 1 
print('a =', a, '; b =', b)

a = [2 3 3 4 5 6] ; b = [2 3]


In [28]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a[:2].copy()
b += 1 
print('a =', a, '; b =', b)

a = [1 2 3 4 5 6] ; b = [2 3]


#### block, vstack, hstack

In [31]:
A = np.ones((2, 2))
B = np.eye(2, 2)
C = np.zeros((2, 2))
D = np.diag((-3, -4))

np.block([[A, B], [C, D]])

array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.],
       [ 0.,  0., -3.,  0.],
       [ 0.,  0.,  0., -4.]])

In [32]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
a = np.array((1, 2, 3))
b = np.array((4, 5, 6))
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
a = np.array([1, 2 ,3])
b = np.array([4, 5, 6])
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [35]:
a = np.array((1, 2, 3))
b = np.array((4, 5, 6))
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])