## Numpy

In [1]:
import numpy as np 

#### 1D, 2D and 3D numpy array

In [2]:
array1D = np.array([45, 2, 4, 7, 8])
array2D = np.array([[5, 4],[8, 4]])
array3D = np.array([[[1, 5],[4, 8]],[[7, 9],[5, 5]]])

In [3]:
array1D

array([45,  2,  4,  7,  8])

In [4]:
array2D

array([[5, 4],
       [8, 4]])

In [5]:
array3D

array([[[1, 5],
        [4, 8]],

       [[7, 9],
        [5, 5]]])

#### dtype

In [6]:
a = np.array([127, 128, 129, 260], dtype=np.int8)
a

array([ 127, -128, -127,    4], dtype=int8)

####  arange, linspace, eye, diag, zeros, ones

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [9]:
np.arange(2, 4, 0.3)

array([2. , 2.3, 2.6, 2.9, 3.2, 3.5, 3.8])

In [10]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [13]:
np.diag([1, 8, 3])

array([[1, 0, 0],
       [0, 8, 0],
       [0, 0, 3]])

In [14]:
np.diag([1, 8, 3],1)

array([[0, 1, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [15]:
x = np.arange(9.0).reshape(3, 3)
x

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [16]:
np.diag(x)

array([0., 4., 8.])

In [17]:
a = np.array([[8,12],[3,7]])
np.diag(a)

array([8, 7])

In [18]:
np.zeros((3, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [19]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### mutable or immutable ???

In [20]:
a = np.array([1, 2, 3, 4, 5, 6]) # numpy arrays are mutable 
b = a[:2]
b += 1 
print('a =', a, '; b =', b)

a = [2 3 3 4 5 6] ; b = [2 3]


In [21]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a[:2].copy()
b += 1 
print('a =', a, '; b =', b)

a = [1 2 3 4 5 6] ; b = [2 3]


#### block, vstack, hstack

In [22]:
A = np.ones((2, 2))
B = np.eye(2, 2)
C = np.zeros((2, 2))
D = np.diag((-3, -4))

np.block([[A, B], [C, D]])

array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.],
       [ 0.,  0., -3.,  0.],
       [ 0.,  0.,  0., -4.]])

In [23]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
a = np.array((1, 2, 3))
b = np.array((4, 5, 6))
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
a = np.array([1, 2 ,3])
b = np.array([4, 5, 6])
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [26]:
a = np.array((1, 2, 3))
b = np.array((4, 5, 6))
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

#### split, hsplit, vsplit

In [27]:
x = np.arange(9.0)
np.split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [28]:
y = np.arange(16.0).reshape(4, 4)
np.split(y, 2, axis=1)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [29]:
x = np.arange(8.0)
np.split(x, [3, 5, 6, 10])

[array([0., 1., 2.]),
 array([3., 4.]),
 array([5.]),
 array([6., 7.]),
 array([], dtype=float64)]

In [30]:
np.hsplit(np.arange(16.0).reshape(4, 4), 2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [31]:
np.vsplit(np.arange(16.0).reshape(4, 4), 2)

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

#### Array vs Lists 

In [32]:
L = [1, 2, 3]
A = np.array([1, 2, 3])
for e in L:
    print(e)

for e in A: 
    print(e)

1
2
3
1
2
3


In [33]:
L.append(4)
print(L)
A.append(4) # doesn't work, append exists in the module level, not in arrays
print(A)     

[1, 2, 3, 4]


AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [34]:
L + [5]

[1, 2, 3, 4, 5]

In [35]:
print(A)
print(np.array([4]))
print(A + np.array([4]))
print(A + np.array([4, 5, 6]))

[1 2 3]
[4]
[5 6 7]
[5 7 9]


In [36]:
A + np.array([4,5]) # doesn't work


ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [37]:
print(A)
print(L)
print(2 * A)
print(2 * L)
print(L + L)

[1 2 3]
[1, 2, 3, 4]
[2 4 6]
[1, 2, 3, 4, 1, 2, 3, 4]
[1, 2, 3, 4, 1, 2, 3, 4]


In [38]:
L2 = []
for e in L: 
    L2.append(e + 3)
print(L2)

[4, 5, 6, 7]


In [39]:
l2 = [e + 3 for e in L]
L2

[4, 5, 6, 7]

In [40]:
l2 = []
for e in L:
    L2.append(e**2)
L2

[4, 5, 6, 7, 1, 4, 9, 16]

In [41]:
print(A)
print(A**2)

[1 2 3]
[1 4 9]


In [42]:
print(np.sqrt(A))
print(np.log(A))
print(np.exp(A))
print(np.tanh(A))

[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]
[ 2.71828183  7.3890561  20.08553692]
[0.76159416 0.96402758 0.99505475]


In [43]:
# Numpy Slower than List

#### The Dot Product 

In [44]:
a = np.array([1, 2])
b = np.array([3, 4])

print(a * b)
# --------------------------
dot = 0
for e, f in zip(a, b):
  dot += e*f
print(dot)
# --------------------------
dot = 0
for i in range(len(a)):
  dot += a[i] * b[i]
print(dot)
dot = 0
# --------------------------
print(np.sum(a * b))
# --------------------------
print(np.dot(a, b))
# --------------------------
print((a * b).sum())
# --------------------------
print(a.dot(b))
# --------------------------
print(b.dot(a))
# --------------------------
print(a @ b)

[3 8]
11
11
11
11
11
11
11
11


#### Computing Second Norm of an Array 

In [45]:
print(a)
mag1 = np.sqrt((a * a).sum())
print(mag1)
mag2 = np.linalg.norm(mag1)
print(mag2)

[1 2]
2.23606797749979
2.23606797749979


In [46]:
cos_angle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))
cos_angle

0.9838699100999074

In [47]:
angle = np.arccos(cos_angle)
angle

0.17985349979247847

#### Matrices 

In [48]:
L = [[1, 2], [3, 4]] # python list 
print(L)
print(L[0])
print(L[0][1])
# --------------------------
A = np.array([[1, 2], [3, 4]]) # numpy array 
print(A)
print(A[0][1])
print(A[0, 1])
print(A[:, 0])
print(A.T)

# --------------------------
print(np.exp(L))
print(np.exp(A))

[[1, 2], [3, 4]]
[1, 2]
2
[[1 2]
 [3 4]]
2
2
[1 3]
[[1 3]
 [2 4]]
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


Numpy already knows the structure of your List. If you ever need to pass a list to scipy or numpy, you DO NOT need to convert it to an array.

In [49]:
print(A)
B = np.array([[1, 2, 3], [4, 5, 6]])

print(B)
print(A.dot(B))
print(A.dot(A))
# error! inner dimensions must match
A.dot(B.T)

[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]]
[[ 9 12 15]
 [19 26 33]]
[[ 7 10]
 [15 22]]


ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

#### linear algebra --> det, inv, trace

In [69]:
print(A)
print('--------------------------------------')
print(np.linalg.det(A))
print('--------------------------------------')
print(np.linalg.inv(A))
print('--------------------------------------')
print(np.linalg.inv(A).dot(A))
print('--------------------------------------')
print(np.trace(A))
print('--------------------------------------')
print(np.diag(A))
print('--------------------------------------')
print(np.diag([1, 4]))

[[1 2]
 [3 4]]
--------------------------------------
-2.0000000000000004
--------------------------------------
[[-2.   1. ]
 [ 1.5 -0.5]]
--------------------------------------
[[1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 1.00000000e+00]]
--------------------------------------
5
--------------------------------------
[1 4]
--------------------------------------
[[1 0]
 [0 4]]


#### Eigendecomposition of a matrix

In [72]:
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [73]:
Lam, V = np.linalg.eig(A)
print(Lam)
print('--------------------------------------')
print(V)
print('--------------------------------------')
print(V[:, 0] * Lam[0] == A @ V[:, 0])
print('--------------------------------------')
print(V[:, 0] * Lam[0], A @ V[:, 0])
print('--------------------------------------')
print(np.allclose(V[:, 0] * Lam[0], A @ V[:, 0]))
print('--------------------------------------')
print(np.allclose(V @ np.diag(Lam), A @ V))

[-0.37228132  5.37228132]
--------------------------------------
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
--------------------------------------
[ True False]
--------------------------------------
[ 0.30697009 -0.21062466] [ 0.30697009 -0.21062466]
--------------------------------------
True
--------------------------------------
True


#### Solving Linear Systems

In [74]:
A = np.array([[1, 1], [1500, 4000]])
b = np.array(([2200, 5050000]))

print(np.linalg.solve(A, b))
print('--------------------------------------')
print(np.linalg.inv(A).dot(b)) # don't do this 

[1500.  700.]
--------------------------------------
[1500.  700.]
