## Pandas 
Practice from Dr. Shokrizadeh's Pandas tutorial

In [1]:
import pandas as pd 

In [2]:
# Loading in data 
df = pd.read_csv('insurance.csv')
df.head(10)

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520
5   31  female  25.740         0     no  southeast   3756.62160
6   46  female  33.440         1     no  southeast   8240.58960
7   37  female  27.740         3     no  northwest   7281.50560
8   37    male  29.830         2     no  northeast   6406.41070
9   60  female  25.840         0     no  northwest  28923.13692

In [3]:
df.tail()

age     sex    bmi  children smoker     region     charges
1333   50    male  30.97         3     no  northwest  10600.5483
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603

In [4]:
type(df)

pandas.core.frame.DataFrame

In [5]:
# saving dataframe to a csv file 
df.to_csv('test.csv')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [7]:
# selectiing rows and columns 
df[0, 0]    # doesn't work

KeyError: (0, 0)

In [8]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [9]:
# columns can be assigned 
df.columns = ['Age', 'Sex', 'BMI', 'Children', 'Smoker', 'Region', 'Charges']

In [10]:
df.columns

Index(['Age', 'Sex', 'BMI', 'Children', 'Smoker', 'Region', 'Charges'], dtype='object')

In [11]:
df['BMI']

0       27.900
1       33.770
2       33.000
3       22.705
4       28.880
         ...  
1333    30.970
1334    31.920
1335    36.850
1336    25.800
1337    29.070
Name: BMI, Length: 1338, dtype: float64

In [12]:
df[['BMI']]

BMI
0     27.900
1     33.770
2     33.000
3     22.705
4     28.880
...      ...
1333  30.970
1334  31.920
1335  36.850
1336  25.800
1337  29.070

[1338 rows x 1 columns]

In [13]:
df[['Age', 'Smoker']]

Age Smoker
0      19    yes
1      18     no
2      28     no
3      33     no
4      32     no
...   ...    ...
1333   50     no
1334   18     no
1335   18     no
1336   21     no
1337   61    yes

[1338 rows x 2 columns]

In [14]:
type(df['Age'])

pandas.core.series.Series

In [15]:
type(df[['Age', 'Smoker']])

pandas.core.frame.DataFrame

In [16]:
df.iloc[0]

Age                19
Sex            female
BMI              27.9
Children            0
Smoker            yes
Region      southwest
Charges     16884.924
Name: 0, dtype: object

In [17]:
df.loc[0]

Age                19
Sex            female
BMI              27.9
Children            0
Smoker            yes
Region      southwest
Charges     16884.924
Name: 0, dtype: object

In [18]:
s = pd.Series(list("abcdef"), index=[49, 48, 47, 0, 1, 2])
s

49    a
48    b
47    c
0     d
1     e
2     f
dtype: object

In [19]:
s.loc[47]

'c'

In [20]:
s.iloc[2]

'c'

In [21]:
df[df['Age'] > 35]

Age     Sex    BMI  Children Smoker     Region      Charges
6      46  female  33.44         1     no  southeast   8240.58960
7      37  female  27.74         3     no  northwest   7281.50560
8      37    male  29.83         2     no  northeast   6406.41070
9      60  female  25.84         0     no  northwest  28923.13692
11     62  female  26.29         0    yes  southeast  27808.72510
...   ...     ...    ...       ...    ...        ...          ...
1329   52    male  38.60         2     no  southwest  10325.20600
1330   57  female  25.74         2     no  southeast  12629.16560
1332   52  female  44.70         3     no  southwest  11411.68500
1333   50    male  30.97         3     no  northwest  10600.54830
1337   61  female  29.07         0    yes  northwest  29141.36030

[764 rows x 7 columns]

In [22]:
df[df['Smoker'] == 'yes']

Age     Sex     BMI  Children Smoker     Region      Charges
0      19  female  27.900         0    yes  southwest  16884.92400
11     62  female  26.290         0    yes  southeast  27808.72510
14     27    male  42.130         0    yes  southeast  39611.75770
19     30    male  35.300         0    yes  southwest  36837.46700
23     34  female  31.920         1    yes  northeast  37701.87680
...   ...     ...     ...       ...    ...        ...          ...
1313   19  female  34.700         2    yes  southwest  36397.57600
1314   30  female  23.655         3    yes  northwest  18765.87545
1321   62    male  26.695         0    yes  northeast  28101.33305
1323   42  female  40.370         2    yes  southeast  43896.37630
1337   61  female  29.070         0    yes  northwest  29141.36030

[274 rows x 7 columns]

In [23]:
df['Sex'] == 'male'

0       False
1        True
2        True
3        True
4        True
        ...  
1333     True
1334    False
1335    False
1336    False
1337    False
Name: Sex, Length: 1338, dtype: bool

In [24]:
type(df['Sex'] == 'male')

pandas.core.series.Series

In [25]:
# by the way, this works with Numpy too 
import numpy as np 
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
A[A % 2 == 0]

array([0, 2, 4, 6, 8])

In [27]:
df.values

array([[19, 'female', 27.9, ..., 'yes', 'southwest', 16884.924],
       [18, 'male', 33.77, ..., 'no', 'southeast', 1725.5523],
       [28, 'male', 33.0, ..., 'no', 'southeast', 4449.462],
       ...,
       [18, 'female', 36.85, ..., 'no', 'southeast', 1629.8335],
       [21, 'female', 25.8, ..., 'no', 'southwest', 2007.945],
       [61, 'female', 29.07, ..., 'yes', 'northwest', 29141.3603]],
      dtype=object)

In [28]:
A = df[['Sex', 'Smoker']].values
A

array([['female', 'yes'],
       ['male', 'no'],
       ['male', 'no'],
       ...,
       ['female', 'no'],
       ['female', 'no'],
       ['female', 'yes']], dtype=object)

In [29]:
type(A)

numpy.ndarray

In [30]:
# write a dataframe to file 
smalldf = df[['Sex', 'Smoker']]
smalldf.to_csv('smalldf.csv')


In [31]:
# what if we don't want an index column?
smalldf.to_csv('smalldf_2.csv', index=False)

### The apply() function 

In [32]:
def bmi_to_integer(row):
    return int(row['BMI'])
df.apply(bmi_to_integer, axis=1)

0       27
1       33
2       33
3       22
4       28
        ..
1333    30
1334    31
1335    36
1336    25
1337    29
Length: 1338, dtype: int64

In [33]:
df['BMI-->integer'] = df.apply(bmi_to_integer, axis=1)

In [34]:
df.head()

Age     Sex     BMI  Children Smoker     Region      Charges  BMI-->integer
0   19  female  27.900         0    yes  southwest  16884.92400             27
1   18    male  33.770         1     no  southeast   1725.55230             33
2   28    male  33.000         3     no  southeast   4449.46200             33
3   33    male  22.705         0     no  northwest  21984.47061             22
4   32    male  28.880         0     no  northwest   3866.85520             28